### ISSUE TITLE
stable repo update ?!

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.find-my-iphone#1]
_From @Apollon77 on May 10, 2017 10:27_

Hey, 

Stable Repo still has v 1.0.3. When still the most stable version, ebverything great, if not please update in stable-repo.

(see https://github.com/ioBroker/ioBroker.repositories)

Thanx for checking

Ingo F

_Copied from original issue: soef/ioBroker.find-my-iphone#7_

**Comment by jogibear9988** [comment]
_From @Apollon77 on July 14, 2017 14:10_

? :-)

**Comment by Apollon77** [comment]
A new adapter will replace this one. Is already in beta repo. Try this please https://github.com/PfisterDaniel/ioBroker.apple-find-me
