### ISSUE TITLE
Funktion eingestellt

### ISSUE THREAD

**Issue by t1m02k16** [iobroker-community-adapters/ioBroker.find-my-iphone#13]
Habe heute durch zufall gesehen, dass der Adapter nicht mehr funktioniert. Bekomme jedoch keine Fehlermeldung...

**Comment by Apollon77** [comment]
Mal neu Eingeloggt und so?

**Comment by t1m02k16** [comment]
Alles versucht. Extra falsches PW eingebene usw... Adapter ist grün, klappt aber nichts. Geht es bei dir noch?

**Comment by Apollon77** [comment]
A new adapter will replace this one. Is already in beta repo. Try this please https://github.com/PfisterDaniel/ioBroker.apple-find-me
