### ISSUE TITLE
Compatibility check and testing for Node.js 14 and 16

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.find-my-iphone#45]
Dear Adapter develop,

Node.js 14 is now available for a year and Node.js 16 was release just some days ago and will become LTS by October 2021. We plan to update the ioBroker Node.js recommendation (currently 12.x) to 14.x later this year.

Please check your adapter with Node.js 14 especially, and ideally also directly with Node.js 16

Please add both versions to the adapter testing which is executed on commits.

If your adapter requires a certain minimum version of Node.js please set the 'engine' setting in package.json accordingly! Please also do this if the adapter is not able to work in certain Node.js versions, so that ioBroker can prevent users from installing te adapter if not compatible!

On questions please talk to us at https://github.com/ioBroker/ioBroker.js-controller/issues/1138 

Please close the issue after you checked it.

Thank you very much for your support!

**Comment by thomasklein1975** [comment]
Hi,

I have this in my log:

`host.raspberrypi-iob	2021-09-21 08:50:35.013	error	instance system.adapter.find-my-iphone.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi-iob	2021-09-21 08:50:35.013	error	Caught by controller[0]: }
host.raspberrypi-iob	2021-09-21 08:50:35.013	error	Caught by controller[0]: ]
host.raspberrypi-iob	2021-09-21 08:50:35.013	error	Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js'
host.raspberrypi-iob	2021-09-21 08:50:35.012	error	Caught by controller[0]: '/opt/iobroker/node_modules/soef/soef.js',
host.raspberrypi-iob	2021-09-21 08:50:35.012	error	Caught by controller[0]: requireStack: [
host.raspberrypi-iob	2021-09-21 08:50:35.012	error	Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi-iob	2021-09-21 08:50:35.012	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
host.raspberrypi-iob	2021-09-21 08:50:35.012	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:933:32)
host.raspberrypi-iob	2021-09-21 08:50:35.011	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
host.raspberrypi-iob	2021-09-21 08:50:35.011	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1068:30)
host.raspberrypi-iob	2021-09-21 08:50:35.011	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js:15:20)
host.raspberrypi-iob	2021-09-21 08:50:35.011	error	Caught by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1271:27)
host.raspberrypi-iob	2021-09-21 08:50:35.011	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:88:18)
host.raspberrypi-iob	2021-09-21 08:50:35.010	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:957:19)
host.raspberrypi-iob	2021-09-21 08:50:35.010	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:730:27)
host.raspberrypi-iob	2021-09-21 08:50:35.010	error	Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
host.raspberrypi-iob	2021-09-21 08:50:35.010	error	Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js
host.raspberrypi-iob	2021-09-21 08:50:35.010	error	Caught by controller[0]: - /opt/iobroker/node_modules/soef/soef.js
host.raspberrypi-iob	2021-09-21 08:50:35.009	error	Caught by controller[0]: Require stack:
host.raspberrypi-iob	2021-09-21 08:50:35.009	error	Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/soef/../iobroker.admin/lib/utils'
host.raspberrypi-iob	2021-09-21 08:50:35.009	error	Caught by controller[0]: ^
host.raspberrypi-iob	2021-09-21 08:50:35.008	error	Caught by controller[0]: throw err;
host.raspberrypi-iob	2021-09-21 08:50:35.008	error	Caught by controller[0]: internal/modules/cjs/loader.js:888`

Versions:
`Node.js: v14.17.0 
NPM: 6.14.13`

It would be great if I could get some help how to fix this.
